#!/usr/bin/bash
set=$(echo -e "day\nnight" | dmenu -p "day or night?")
[ "$set" == "day" ] && xrandr --output eDP-1 --gamma 1:1:1 --brightness $(dmenu -p brightness < /dev/null)
[ "$set" == "night" ] &&  xrandr --output eDP-1 --gamma 1.0:0.88:0.76 --brightness $(dmenu -p brightness < /dev/null)

