#!/usr/bin/env bash
# ffsrec(){
# 	# https://girishjoshi.io/post/screen-recording-with-webcam-overlay-using-ffmpeg/
# 	# https://trac.ffmpeg.org/wiki/Capture/ALSA

# 	local today=$(date +"%Y-%m-%d")

# 	# ffmpeg \
# 	# 	-f x11grab \
# 	# 	-video_size 2560x1080 \
# 	# 	-framerate 25 \
# 	# 	-i $DISPLAY \
# 	# 	-f alsa \
# 	# 	-i hw:3 \
# 	# 	-c:v libx264 \
# 	# 	-preset ultrafast \
# 	# 	-c:a aac "${today}--${1:-VID}.mp4"

# 	# echo -n "path: "
# 	# read dir
# 	# local path="~/Videos/casts/${dir}/"
# 	# echo $path

# 	local monofile="mono.mp4"

# 	rm -rf /tmp/${monofile}

# 	# ffmpeg \
# 	# 	-f x11grab \
# 	# 	-video_size 2560x1080 \
# 	# 	-framerate 25 \
# 	# 	-i $DISPLAY \
# 	# 	-f alsa \
# 	# 	-i default:2 \
# 	# 	-c:v libx264 \
# 	# 	-preset ultrafast \
# 	# 	-c:a aac "/tmp/${monofile}"

# 	# ffmpeg \
# 	# 	-f x11grab \
# 	# 	-video_size 2560x1080 \
# 	# 	-framerate 25 \
# 	# 	-i $DISPLAY \
# 	# 	-f alsa \
# 	# 	-i default \
# 	# 	-c:v libx264 \
# 	# 	-preset ultrafast \
# 	# 	-c:a aac "/tmp/${monofile}"
today=$(date +"%Y-%m-%d")

name="$(dmenu -fn "monospace:size=14" -nb "#222222" -nf "#bbbbbb" -sb "#d8bb6d" -sf "#222222" -p "video name" < /dev/null)"
file="/home/nyquist/Videos/casts/${today}--${name:-VID}.mp4"

ffmpeg \
	-f x11grab \
	-video_size 1920x1080 \
	-framerate 60 \
	-i $DISPLAY \
	-f pulse \
	-ac 2 \
	-i default \
	-preset ultrafast \
	-af "pan=stereo|FL=FL|FR=FL" \
	"$file" &
wait

set=$(echo -e "y\nn" | dmenu -fn "monospace:size=14" -nb "#222222" -nf "#bbbbbb" -sb "#d8bb6d" -sf "#222222" -p "want to view your video?")

ffplay "$file"

# 		# -c:a aac "/tmp/${monofile}"
# 		# -c:v libx264 \
# 		# -preset ultrafast \

# 	# ffmpeg -i "/tmp/${monofile}" -af "pan=stereo|c0=c0|c1=c0" "/home/nyquist/Videos/casts/youtube/${today}--${1:-VID}.mp4"
# 	# rm -rf $monofile

# 	# ffmpeg -f x11grab -video_size 1366x768 -framerate 30 -i :0.0 \
# 	# -f v4l2 -video_size 320x180 -framerate 30 -i /dev/video0 \
# 	# -filter_complex 'overlay=main_w-overlay_w:main_h-overlay_h:format=yuv444' \
# 	# -vcodec libx264 -preset ultrafast -qp 0 -pix_fmt yuv444p video.mp4

# 	# ffmpeg \
# 	# 	-f x11grab \
# 	# 	-video_size 2560x1080 \
# 	# 	-framerate 25 \
# 	# 	-i $DISPLAY \
# 	# 	-f v4l2 \
# 	# 	-video_size 320x1080 \
# 	# 	-framerate 25 \
# 	# 	-i /dev/video0 \
# 	# 	-filter_complex 'overlay=main_w-overlay_w:main_h-overlay_h:format=yuv444' \
# 	# 	-f alsa \
# 	# 	-i hw:3 \
# 	# 	-c:v libx264 \
# 	# 	-preset ultrafast \
# 	# 	-c:a aac "${today}--${1:-VID}.mp4"
# 		# -c:a aac "what.mp4"
# }
