#!/usr/bin/env bash
today=$(date +"%Y-%m-%d")

name="$(dmenu -fn "monospace:size=14" -nb "#222222" -nf "#bbbbbb" -sb "#d8bb6d" -sf "#222222" -p "video name" < /dev/null)"

cd /home/nyquist/Videos/casts/

file="${today}--${name:-VID}.mp4"

# Start ffmpeg in the background
ffmpeg \
    -f x11grab \
    -video_size 1920x1080 \
    -framerate 60 \
    -i $DISPLAY \
    -f pulse \
    -ac 2 \
    -i default \
    -preset ultrafast \
    -af "pan=stereo|FL=FL|FR=FL" \
    "$file" &

[[ "$!" -gt 0 ]] && notify-send -t 2000 "recording started" || exit
# Save ffmpeg PID
echo $! > /tmp/ffsrec_ffmpeg.pid

# Keep script alive until ffmpeg finishes
wait $!

# kill with this command
# $ kill -SIGINT $(cat /tmp/ffsrec_ffmpeg.pid)

# Cleanup
rm -f /tmp/ffsrec_ffmpeg.pid

GTK_THEME=Adwaita:dark yad --title "youtube-upload" \
  --center \
  --text "do you want to view your video?" \
  --button="yes:0" \
  --button="no:1" && ffplay "$file"

GTK_THEME=Adwaita:dark yad --title "youtube-upload" \
  --center \
  --text "do you want to upload to youtube?" \
  --button="yes:0" \
  --button="no:1" || exit

preform=$(GTK_THEME=Adwaita:dark yad --form \
    --separator="&" \
    --title='youtube-upload' \
    --center \
    --width=700 \
    --height=500 \
    --field='Title' "$name" \
    --field='Description:TXT' '' \
    --field='Privacy:CB' 'private!public!unlisted'\
    --field='tags (seperate with commas)' '')

form="$(tr '\n' '`' < <(echo -e "$preform"))"
title="$(echo $form | cut -f1 -d '&')"
predescription="$(echo $form | cut -f2 -d '&')"
description="$(tr '`' '\n' < <(echo -e "$predescription"))"
privacy="$(echo $form | cut -f3 -d '&')"
tags="$(echo $form | cut -f4 -d '&')"

# for debuging purposes
#echo -e "title:\n\t$title\ndescription:\n$description\nprivacy:\n\t$privacy\ntags:\n\t$tags"

/usr/local/bin/youtube-upload "$file" \
	--title "$title" \
	--description "$description" \
	--privacy "$privacy" \
	--tags "$tags" && notify-send "upload succeeded" || notify-send "did not upload"
