#!/usr/bin/env bash

cd "$1"

tstdir=/usr/local/share/tst/
type=(*.*)
clear

for file in ${type[@]}; do
    case $file in
        *.nasm) gdb -x ${tstdir}/gdb/global.gdb -x ${tstdir}/gdb/nasm.gdb tst;;
        *.c) gdb -x ${tstdir}/gdb/global.gdb -x ${tstdir}/gdb/c.gdb tst;;
        *.cpp) gdb -x ${tstdir}/gdb/global.gdb -x ${tstdir}/gdb/cpp.gdb tst;;
    esac
done
