#!/usr/bin/env bash

cd "$1"

type=(*.*)
clear

for file in ${type[@]}; do
    case $file in
        *.cpp)  g++ -g -Wall -Wextra tst.cpp -o tst -lm
                ./tst
                break
        ;;

        *.s|S)  gcc -fno-asynchronous-unwind-tables -g -c -Wall -Wextra tst.s
                gcc -o tst tst.o
                ./tst
                break
        ;;

        *.c)    gcc -g -Wall -Wextra tst.c -o tst -lm
                ./tst
                break
        ;;

        *.pl)   LANG=C ./tst.pl; break;;

        *.nasm) nasm -f elf64 -g -F dwarf tst.nasm
                gcc -o tst tst.o -no-pie
                ./tst
                break
        ;;

        *.sed)  sed -f tst.sed file; break;;

        *)
            ./tst.*
        ;;
    esac
done
