#!/usr/bin/env bash

tstdir=/usr/local/share/tst/
cd $tstdir
templatePath=${tstdir}templates/"$1"/

open(){
	if [[ ! -d "$1" ]]; then
		return
	fi

    cd $1
    rm -R *

    cat ${templatePath}/"$2" > tst."$1"

    if [[ "$1" == "sed" ]]; then
        echo "sed"
        cp ${templatePath}/file .
    fi

    chmod +x tst."$1"
}

if (( $# > 0 )); then
    while (( $# != 0 )); do
        case $1 in
                py|c|cpp|js|sh|pl|s|vim|lua|nasm|bash|sed)
                break
            ;;
            *)
                echo "argument \"${1}\" is not valid"
                exit 1
            ;;
        esac
    done
else
    echo "arguments are required"
    exit 2
fi

if (( $# > 1 )); then
    open $1 "$2"
else
    open $1 "default"
fi

if [[ "$1" == "sed" ]]; then
    nvim -S "${tstdir}/mappings.vim" -o tst."$1" file
else
    nvim -S "${tstdir}/mappings.vim" tst."$1" 
fi
